version: "3.8"
services:

    # PHP Service
    app:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        ports:
            - 8000:8000
        depends_on:
            - database
    database:
      image: postgres:latest
      environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
      ports: 
      - "5444:5432"